### ISSUE TITLE
Cannot reproduce demo

### ISSUE THREAD

**Issue by robertoberlim** [stianst/keycloak-containers-demo#2]
While running 'docker run --name devnation-keycloak -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -p 8080:8080 --net devnation-network devnation-keycloak' I got  
21:06:45,967 FATAL [org.keycloak.services] (ServerService Thread Pool -- 72) java.util.ServiceConfigurationError: org.keycloak.authentication.AuthenticatorFactory: Provider org.keycloak.experimental.magic.MagicLinkFormAuthenticatorFactory could not be instantiated

**Comment by stianst** [comment]
Just happens that I upgraded the demo to Keycloak 9.0.2 yesterday, so should be working fine now.
