### ISSUE TITLE
minor documentation issue

### ISSUE THREAD

**Issue by robertoberlim** [stianst/keycloak-containers-demo#3]
The configured port on demo-mail is 1025, not 25.

**Comment by robertoberlim** [comment]
Also in the Readme:
Find the js-console client again and add the _myclaim_ as a default client scope. No scope with that name exists.

**Comment by runeksvendsen** [comment]
@stianst Please merge #5. It fixes this issue.

**Comment by stianst** [comment]
Thanks, merged
